### GET request to example server
GET http://localhost:8080/url

###

POST http://localhost:8080/url/add
Content-Type: application/json

{
  "url": "http://example49.com",
  "displayName": "Example24rwqff",
  "status": 200
}

###

DELETE http://localhost:8080/url/delete/13