### GET request to example server
GET http://localhost:8080/url

###

POST http://localhost:8080/url/add
Content-Type: application/json

{
  "id": 6,
  "url": "http://example20.com",
  "displayName": "Example",
  "status": 200,
  "lastChecked": "2024-07-02T12:34:56"
}