### GET request to example server
GET http://localhost:8080/url

###

POST http://localhost:8080/url/add
Content-Type: application/json

{
  "url": "https://httpstat.us/300",
  "displayName": "ehsfe3245r"
}

###

DELETE http://localhost:8080/url/delete/10

###

PUT http://localhost:8080/url/update/9?newDisplayName=49example49

###

DELETE http://localhost:8080/url/delete/all

###